### ISSUE TITLE
Multiple taps for qgis

### ISSUE THREAD

**Issue by lifepillar** [Homebrew/homebrew-science#1036]
Given that
- the current qgis formula in homebrew/science installs an old version of QGis,
- it's broken (at least) in Mavericks (see #631 and #716),
- QGis is also supported by [homebrew/osgeo4fmac](https://github.com/OSGeo/homebrew-osgeo4mac) with an up-to-date release that builds in Mavericks,
- having QGis in more than one tap is confusing for the user,

I propose that either qgis is removed from homebrew/science or homebrew/osgeo4mac is merged with homebrew/science. I think that it makes sense to have a tap for geospatial formulas with dedicated maintainers, so I am for the former option.

**Comment by andreabedini** [comment]
@dakcarto will `homebrew/geospatial` follow the same rules as the main `homebrew/homebrew`? I'm asking because formulas that build `.app` native OSX applications [are not welcome](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Acceptable-Formulae.md#stuff-that-builds-a-app) in the main repository. They suggest to head to use [caskroom.io](http://caskroom.io) instead.

**Comment by dakcarto** [comment]
Hi @andreabedini. You bring up an interesting topic, which I have spent considerable time contemplating. The restriction of .app bundles, as outlined in the [referenced docs paragraph](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Acceptable-Formulae.md#stuff-that-builds-a-app), is clear, but does not go into the different uses of an .app bundle in very much depth. The reality of Homebrew's repos is different, otherwise there would be no need for the `linkapps` command.

The bundling extent of .app directories can dictate very different approaches to software installations on Mac, and shouldn't be grouped together, just because an .app bundle is created:

  * **Minimal .app bundle** - This can be merely a wrapper for an executable, whose dependency stack, or even actual executable, lives elsewhere (e.g. Homebrew prefix), and is akin to a [Linux .desktop file](https://developer.gnome.org/integration-guide/stable/desktop-files.html.en), whereby it just allows the software to be comfortably integrated into the user's desktop/Finder and app launchers as a discrete application object. Of course, the .app bundle doesn't need to launch a GUI app, and can provide a nice means of controlling servers, etc. as well.

  * **Full (drag-n-drop) .app bundle** - Such standalone bundled apps are well-suited for cask installation. While many geospatial programs _can_ be fully bundled, this does not necessarily mean they _should_ be, especially if their major dependencies can be installed in a shared manner, a la via Homebrew.

Like other scientific software domains, geospatial day-to-day workflows often can not be accomplished in one application, especially when using FOSS4Geo software. Usually a non-casual user requires a _geospatial software stack_ and knowledge of scripting APIs. For example, the user can then take solace in the fact that GDAL/OGR, and its particular plugins, will work the same in a variety of apps or as a standalone tool or Python module and is separately upgradeable, _if_ all of the .app bundles built against it do not independently bundle their own copy of it.

This is the approach I have taken in the OSGeo4Mac tap, in that all .app bundles are minimally bundled. Using a similar approach for a `homebrew/geospatial` tap, I do not think those bundles should be considered 'unwelcome' in Homebrew. Indeed, the Homebrew package ecosystem allows those minimally bundled apps to exist as such.

Fully bundled apps/installations have their place, e.g. casual users and large roll-outs in learning institutions, etc. and many of the geospatial programs are available in that way from their respective web sites. In general, I think Homebrew and its taps are more for users willing to work with an efficient package manager to build a software stack to actually get work done with the latest software, or maybe to hack away at it.

As an example of a minimally bundled app that _can_ be bundled more, but _shouldn't_ in Homebrew, consider QGIS, which ostensibly seems like a good candidate for cask-only:

  * User-friendly GUI .app built off of Qt
  * Offers a command line interface
  * Offers C++ dev libraries
  * Offers Python dev modules
  * Integrates with an increasing number of large external tool sets via Processing plugin
  * Built off of many shared libraries

Only the first bullet point needs an .app bundle. Fully bundling all of the rest just leads to bloating and inflexible isolation of functionality when using other apps (similar to the everything-in-Xcode.app versus Xcode CLT). A fully bundled .app is often a hindrance to further development based off of its components.

This is why the [OSGeo4W project](http://trac.osgeo.org/osgeo4w/), on Windows, installs a shared geospatial stack in a single directory rather than separately packaged apps; and why I am modeling the second phase of the OSGeo4Mac project on that approach, with the goal of using a `homebrew/geospatial` tap as a backend.

**Comment by andreabedini** [comment]
Hi @dakcarto, thanks for sharing your elaborate thoughts :)  I'm very happy with a minimal bundle, I reckon full-stack installation should be left to the user and doesn't belong to a system like homebrew. I had a look at `OSGeo/homebrew-osgeo4mac`. Just to check if we are on the same page, I think we should avoid duplicating formulas already in homebrew (unless of course they will be moved to the new tap). I'm building qgis with all dependencies from the main repo and it seems to be working so far. I must admit I don't know qgis much and my opinions might be completely unworthy of any attention! I'm here basically because I tried to install it on my mac and couldn't find a decent way of doing so :P

**Comment by iMichka** [comment]
`qgis` was removed from `homebrew-science` with #4688. Closing.
