### ISSUE TITLE
openblas installation failure

### ISSUE THREAD

**Issue by saketkc** [Homebrew/homebrew-science#1264]
I have not been able to debug this. See line 19:
http://pastebin.com/PcLT2BPh

For some reason, `/auto/cmb-ar` gets substituted when it should have been `ar`. I am puzzled as the Makefile looks fine: a manual installation with `make FC=/auto/cmb-06/as/skchoudh/linuxbrew/bin/gfortran libs netlib shared
` inside the folder seems to be working fine.

**Comment by dpo** [comment]
@saketkc Any better luck with the updated OpenBLAS?

**Comment by saketkc** [comment]
Unfortunately, no.

**Comment by tdsmith** [comment]
The detection is here: https://github.com/xianyi/OpenBLAS/blob/a124637329d852b9d696d892d1c055f92c153a93/c_check#L28-L36

It's invoked here: https://github.com/xianyi/OpenBLAS/blob/80bf3e6a3525f558a9fde2514622313c991c091f/Makefile.prebuild#L24-L25

I hazard that this is only manifesting in Homebrew because Homebrew sets CC.

Closing as an upstream issue; let me know if you disagree.
