### ISSUE TITLE
brew install r-gui failed to install on OS X 10.10.1

### ISSUE THREAD

**Issue by tgerke** [Homebrew/homebrew-science#1621]
Gist at: https://gist.github.com/1d9dcb208f76dd180fbd

Thanks for any help!

**Comment by dpo** [comment]
It builds fine here. Perhaps you had installed `r` previously with non-default options (e.g, you built it with `gcc`)? Could you try `brew uninstall r; brew install r-gui`? If that doesn't work, let's try the more drastic `brew uninstall $(brew deps r-gui); brew install r-gui`.

**Comment by tgerke** [comment]
I had installed r earlier with a standard brew install r. I uninstalled and tried each of your suggestions, but got the same CompileC build command failure in each case. It's puzzling: I'm working with a fresh install of Yosemite, and had only installed Python/virtualenv/XQuartz/r prior to trying the r-gui build. If there's other information I could provide that would be useful, I'm happy to send it along.

**Comment by dpo** [comment]
Ah I think I may know what's going on. Try to build `r` from source instead of installing the bottle (as I suspect you're doing). There was a problem with the previous bottles and I'm in the process of updating them. Let's try `brew uninstall r; brew install r --build-from-souce; brew install r-gui`.

**Comment by tgerke** [comment]
Brilliant -- worked perfectly. Thanks for your help!

**Comment by dpo** [comment]
Glad it's working. The bottles should be fixed soon.
