### ISSUE TITLE
Improve travisCI

### ISSUE THREAD

**Issue by saketkc** [Homebrew/homebrew-science#1795]
The `travis` setup is pretty buggy. Main issues:

1.  The `test-bot` Builds against head, even after reverting to an older commit. This should be self-explanatory: https://travis-ci.org/Homebrew/homebrew-science/builds/48832792

2.  Tries to reinstall dependencies causing the build timeout to bloat up: https://github.com/Homebrew/homebrew-science/pull/1750#event-223979129

Strategy:

1. `test-bot.rb` recognises github PRs automagically. I tried it here: https://github.com/saketkc/homebrew-science/commit/43acb9ae6d7394fa9ad3ed57ef3aeaf813bf7509
But I have not been able to test this.

2. Can be potentially fixed by checking installed dependencies as in: https://github.com/saketkc/homebrew-science/commit/6b9bed97c9934f0ab3ea139de51a0cc4b960d360

Untested again.

Comments/suggestions/help welcome.

**Comment by dpo** [comment]
I also feel like `brew test-bot` performs a lot of verbose operations, even if you omit `-v`. I wonder if we need a silent version of `test-bot` for TravisCI.

**Comment by dpo** [comment]
@saketkc Have a look at this build on my fork: https://travis-ci.org/dpo/homebrew-science/builds/51329208

It goes through beautifully. Aside from simplifying small things, I essentially made two changes:
1. [Made Homebrew believe that `gcc` is installed](https://github.com/dpo/homebrew-science/blob/f2c865b10570fe65f1f266601cb1703fd98838c1/.travis.yml#L39)
2. Use [`brew install` instead of `brew test-bot`](https://github.com/dpo/homebrew-science/blob/f2c865b10570fe65f1f266601cb1703fd98838c1/travisCI/travis_debug.sh#L18)

Clearly, 2 won't produce a bottle, but at least for the time being we can know whether something builds or not. `brew test-bot` still performs operations in verbose mode and the log size reaches the limit.

**Comment by saketkc** [comment]
@dpo How about piping the results of `test-bot` to a file like we are doing currently?
https://github.com/Homebrew/homebrew-science/blob/master/travisCI/travis.sh#L50

**Comment by saketkc** [comment]
Are we also planning to integrate `--build-bottle`?

**Comment by dpo** [comment]
Yes that would be great.

We should also force symlink the compilers:
https://travis-ci.org/Homebrew/homebrew-science/builds/53218513#L212

**Comment by dpo** [comment]
Is Travis completely disabled at the moment?

**Comment by saketkc** [comment]
It is as good as nothing, I guess. Fails on even simple builds.

**Comment by saketkc** [comment]
Sorry, I see what you are saying. The new PRs are not triggering travis, right?

**Comment by dpo** [comment]
Yeah.

**Comment by dpo** [comment]
Closing, now that we have the new Travis setup.
