### ISSUE TITLE
trilinos with python (dyld: Symbol not found: _PyBool_Type)

### ISSUE THREAD

**Issue by davydden** [Homebrew/homebrew-science#2148]
just installed default trilinos without disabling python. 

when I run executable that's the error I got:
```
dyld: Symbol not found: _PyBool_Type
```

I never use python, so I have no ideas what/if something has to be set up. `numpy` is installed as a dependency, i use the os-x python
```
$ python --version
Python 2.7.6
```

**Comment by tseemann** [comment]
To whoever understands this, here is some likely relevant lines in the formula:

```
  depends_on :python        => :recommended
  depends_on "homebrew/python/numpy"  if build.with? "python"

  args << onoff("-DTrilinos_ENABLE_PyTrilinos:BOOL=", (build.with? "python"))
```

**Comment by iml** [comment]
>If you create an issue, please also create a Gist by running
>
>```
>brew gist-logs <formula name>
>```

**Comment by dpo** [comment]
@davydden Could you give the shortest Python script that reproduces the issue?

**Comment by davydden** [comment]
it's not a python script, it's running anything that is linked against `trilinos`, even unit tests in any other software such as https://github.com/Homebrew/homebrew-science/pull/1299

**Comment by davydden** [comment]
For a moment i use `trilinos --without-python` to make C++ code run (i don't use python anyhow)

**Comment by tdsmith** [comment]
Can't reproduce this. :( `Epetra_BasicPerfTest_test.exe 1 1 1 1 5 -v` succeeds.

**Comment by tdsmith** [comment]
If you stumble across build logs from a build where this manifests, the gisted logs would help diagnose this.

**Comment by davydden** [comment]
will do that later during the week...

**Comment by davydden** [comment]
i reinstalled trilinos with python and indeed `brew test trilinos` works fine and also i can run executables. 

Could that be that this issue appears when executables are runned within the 
```
def install
...
end
```
block? Somewhat related to super-envirnoment and all that stuff?


That was the original place where I saw the problem, namely when installing deal.II formula which executes a minimum number of test programs during installation https://github.com/Homebrew/homebrew-science/blob/master/dealii.rb#L81

@tdsmith could you please try to reproduce it with deal.II?

**Comment by dpo** [comment]
Sorry, I'm not seeing the error in your logs. Could you point us to it?

Are you observing the crashes with OpenMPI or MPICH2?

**Comment by davydden** [comment]
it's a run-time error of C++ executables built against the trilinos library. 
For example a few unit tests which are run here https://github.com/Homebrew/homebrew-science/blob/master/dealii.rb#L81
it's not because those particular unit tests fail in terms of expected results and actual ones, or fail to compile. They just fail to run
```
dyld: Symbol not found: _PyBool_Type
```
moreover, the python part of trilinos is not used in deal.II anyhow, so it's just an issue of trilinos on my computer being linked against some python libs with some symbols which are not available later on during running executables. At least that's my interpretation of what is happening...

i don't think it is related to MPI anyhow, but I use OpenMPI.

**Comment by dpo** [comment]
The trilinos log indicates that it builds against your system Python. Have you tried with Homebrew Python?

**Comment by davydden** [comment]
i installed homebrew's python and then reinstalled trilinos, but still 
```
dyld: Symbol not found: _PyBool_Type
  Referenced from: /usr/local/lib/libpytrilinos.11.dylib
```

**Comment by dpo** [comment]
I can reproduce this. Looks like it may not be new: https://www.mail-archive.com/dealii@dealii.org/msg02973.html

Certainly worth reporting to the Trilinos crew.

**Comment by davydden** [comment]
shall one perhaps modify for a time being `deal.II` formula to use trilinos `--without-python`?

**Comment by dpo** [comment]
Is it a dealII issue of a Trilinos issue? Are you able to run other Trilinos programs?

**Comment by davydden** [comment]
@bangerth did you come across these issues when deal.II is built against Trilinos with python?

**Comment by bangerth** [comment]
@davydden: I have no idea -- I have never consciously built Trilinos with Python. Is this what it does by default? We don't use the PyTrilinos interfaces, so I was never tempted to enable them...

**Comment by dpo** [comment]
I strongly suggest reporting this on the Trilinos mailing list. I'm quite tied up at the moment, so I won't find a time to investigate for a little while.

**Comment by davydden** [comment]
@bangerth it is a default built of trilinos in Homebrew. I guess within Trilinos build system python interfaces are not enabled by default.

@dpo will do so.

**Comment by wfspotz** [comment]
Here is what is happening: the Trilinos build system includes the libpytrilinos library on all link lines even though the only products that need it are the dynamic PyTrilinos shared objects imported with the various Trilinos packages that have Python wrappers.

The Python usage is that from the Python interpreter, PyTrilinos modules get imported and all of the Python C/API functions, types, etc. are provided immediately by the interpreter.  In your case, none of the Python C/API functions, types, etc. are available, so you get a "Symbol not found" error.

I have asked the software engineers in charge of the build system to remove libpytrilinos from the list of libraries in the export Makefiles, but they have not prioritized it.  It is apparently not trivial.  I am kind of amazed, because anyone who builds Trilinos for general use and enables PyTrilinos should run into this problem, but this is the first time I have encountered it outside of Sandia.

A workaround is to remove libpytrilinos from the export Makefile you are using.  I will try to push this issue to a higher priority among the build engineers.

(I am making an assumption that you are using the export Makefiles from Trilinos in your project.  If this is not the case, then you may be seeing the problem due to another, but similar, mechanism I am not yet aware of.)

**Comment by davydden** [comment]
thanks @wfspotz for the clarification. To my understanding, `deal.II` cmake build system reads library list from the trilinos cmake files in the target directory (e.g. `/lib/cmake/Trilinos/TrilinosConfig.cmake`). When trilinos is configured with `python`, we have `Trilinos_LIBRARIES=...;pytrilinos;...`. This consequently leads to inclusion of `libpytrilinos`, as you suggested, as a dependent library of `deal.ii` (here is an excerpt from the cmake configure of deal.ii against trilinos with python):
```
--   TRILINOS_LIBRARIES: 
[...]
/usr/local/lib/libpytrilinos.dylib;
[...]
/usr/local/lib/libmpi.dylib
--   TRILINOS_INCLUDE_DIRS: 
[...]
--   TRILINOS_USER_INCLUDE_DIRS: 
[...]
-- Found TRILINOS
```
So at the end if the day, I think it is indeed so that building trilinos with python pritty much limits its usage within python only, which is a pity. 

@dpo in light of this discussion, what do you think about making `python` an optional dependency? As far as I recall this will allow to have a trilinos `bottle` as the library builds within 60 mins limit? Consequently I would also put `trilinos` as a default option to deal.ii and have it's bottle with all the bells and whistles.

**Comment by dpo** [comment]
That would only resolve the issue for users who don't brew Trilinos `--with-python`, which might result in tricky issues on this tracker. The real solution would be to fix the Trilinos makefiles. I do agree that it would be good to have Trilinos bottles, but that's a different discussion.

@wfspotz If I understand well, this issue seems to make Trilinos pretty much unusable from other libraries if built with Python support. It would be great if you could escalate it and get it resolved. It would also be great to know if it hurts other users.

**Comment by davydden** [comment]
closing this as the issue was fixed via a workaround
