### ISSUE TITLE
BLAST - Do not know how to build MT-safe with compiler g++-5  5.1.0

### ISSUE THREAD

**Issue by tseemann** [Homebrew/homebrew-science#2337]
I've been setting up a fresh linux brew and got this error:

```
==> Downloading ftp://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/2.2.30/ncbi-blast-2.2.30+-src.tar.gz
==> Patching
patching file c++/include/corelib/ncbimtx.inl
==> ./configure --prefix=/bio/linuxbrew/Cellar/blast/2.2.30_1 --libdir=/bio/linuxbrew/Cellar/blast/2.2.30_1/libexec --without-debug --wi
checking whether we are using the GNU C++ compiler... yes
checking whether /bio/linuxbrew/bin/g++-5 accepts -g... yes
adjusted C   compiler: /bio/linuxbrew/bin/gcc-5
adjusted C++ compiler: /bio/linuxbrew/bin/g++-5
configure: error: Do not know how to build MT-safe with compiler /bio/linuxbrew/bin/g++-5  5.1.0
```

I resolved it with

```HOMEBREW_CC=gcc-4.8 brew install blast```

Can we restrict compiler versions in formulae?

**Comment by tdsmith** [comment]
`fails_with :gcc => "5"` should work.

**Comment by sjackman** [comment]
:+1:

**Comment by wookietreiber** [comment]
There seems to be a simple solution to this problem which allows blast 2.2.31 to be built with gcc 5+.

I debugged the configure script on Linux a bit (same problem there) and found out that the internal variable `compiler` is not set correctly. The following allowed me to build successfully on Linux:

```
sed -e '/if test "$with_mt" != "no" ; then/i compiler=GCC' \
    -i src/build-system/configure
```

I expect this little patch to work on homebrew as well.

**Comment by sjackman** [comment]
@wookietreiber Can you send this fix to the upstream developers? github-tools@ncbi.nlm.nih.gov

**Comment by wookietreiber** [comment]
@sjackman I don't think, this is the proper fix to go with, it is more of a hack.

We should rather report the real issue, i.e. that for gcc 5+ the internal variable `compiler` is not set and because of this `configure` fails during the `--with-mt` part.

**Comment by sjackman** [comment]
That's more what I meant, to bring the real issue to the developers' attention so that they can fix it for the next release.

**Comment by wookietreiber** [comment]
Dear NCBI devs,

The `configure` script of blast+ 2.2.31 fails with the --with-mt option on Unix, see also [the GitHub issue for homebrew][1].

I debugged the `configure` script around the `with_mt` part on Linux a bit and found out that the internal variable `compiler` is not set correctly. The 
following allowed me to build successfully on Linux:

     sed -e '/if test "$with_mt" != "no" ; then/i compiler=GCC' \
         -i src/build-system/configure

The patch inserts a line that sets `compiler` to `GCC` just before the `with_mt` part of the configure script. I don't know yet what the reason is that 
`compiler` is not set correctly. This issue only occurs for gcc version >= 5.0 and not with gcc 4.x. This leads me to the conclusion, that there may be an issue 
in the `compiler` recognition part of your `configure` script.

The little patch above with sed is just a hack to make it work on our systems with gcc >= 5.0. It would be really nice if you could fix the issue regarding the 
`compiler` variable, so we don't need this hack to compile blast+ 2.2.31 with gcc >= 5.0.

Thanks in advance and

Best Regards
Christian Krause on behalf of the blast+ community


P.S.: I have set this email up to both CC and Reply-To to the [GitHub issue][1].


[1]: https://github.com/Homebrew/homebrew-science/issues/2337

**Comment by sjackman** [comment]
Thanks, Christian!

**Comment by fabioticconi** [comment]
I know this is a closed issue, but I just stumbled upon this problem and thought I'd give my 2 cents. The fix is actually much simpler than the one proposed. The error lies here:

```
if test "$GCC" = "yes" ; then
   compiler_ver="`$real_CXX -dumpversion 2>&1`"
   case "$compiler_ver" in
     2.95* | 2.96* | 3.* | 4.* )
       compiler="GCC"
       ncbi_compiler="GCC"
       ncbi_compiler_ver="$compiler_ver"
                 WithFeatures="$WithFeatures${WithFeaturesSep}GCC"; WithFeaturesSep=" "
       ;;
   esac
```

As you can see, GCC is recognised but it uses explicit detection of the compiler version. GCC 5.X won't be detected. The fix is just to add ```| 5.*``` after ```4.*```. As GCC versions go up it will happen again and again, sadly.

**Comment by wookietreiber** [comment]
There is a new version of blast+ now: 2.3.0. This problem has apparently been fixed.

**Comment by fabioticconi** [comment]
I see. I have actually the latest version of igblast to work with, so I guess it has inherited the problems of the old blast.
