### ISSUE TITLE
r bottle doesn't include manuals

### ISSUE THREAD

**Issue by echristopherson** [Homebrew/homebrew-science#2378]
The r-3.2.0_1 bottles downloaded from https://homebrew.bintray.com/bottles-science/ don't contain the HTML manual files under R.framework/Versions/3.2/Resources/doc/manual/ which are in the CRAN package. The RStudio cask assumes they are there and shows links for them in its Help tab (lower right pane), but clicking them does nothing (right-clicking and opening in a new window shows a blank page, and copying the link and going there in a browser does the same).

In the CRAN package at http://cran.rstudio.com/bin/macosx/R-3.2.0.pkg the files are in the r.pkg subpackage.

**Comment by tdsmith** [comment]
Hmm; the `--enable-prebuilt-html` switch is not the right solution here.

**Comment by tdsmith** [comment]
texi2any (provided by texinfo) is required to build these.

**Comment by echristopherson** [comment]
I've just read a little about this. Is the normal behavior to generate these at runtime when they're first requested? I'm unsure as to how to trigger that (I'm very new to R), if so. But maybe if it's supposed to work that way using R per se, perhaps the problem lies with RStudio.

**Comment by tdsmith** [comment]
My comments are a little cryptic, sorry! The manuals are compiled to html at build time, and we need to add a build-time dependency on the texinfo formula to the r formula so that we package them; Homebrew can (and I think should) make that change.

There's a separate question about whether html for package documentation is generated statically or whether R should launch a local web server to display help files, compiling them on the fly. This is what the `--enable-prebuilt-html` switch changes; it's not related to the manuals. The current behavior here seems fine to me.

**Comment by tdsmith** [comment]
This should work after `brew update && brew reinstall r`. Thanks for the report.
