### ISSUE TITLE
Correct usage of depends_on "foo" => :build

### ISSUE THREAD

**Issue by tseemann** [Homebrew/homebrew-science#2379]
Looking through all the formulae this is confusion of when to use the ```depends_on :build``` option

Obviously build tools like ```autoconf```, ```cmake``` etc are not needed after compilation, so should be ```:build```.

And pipelines etc that use other binaries clearly need a hard dependency.

The confusion is for libraries. If statically linked, it can be ```:build``` but for most dynamically linked libraries it should **not** be ```:build``` ?

I'm not sure how this works in conjunction with ```:recommended``` and ```cxx11``` for example with libraries like ```boost``` where I think a lot of ```:build``` might be used incorrectly?

Any advice appreciated!

**Comment by tdsmith** [comment]
You're right; dynamically linked libraries must not be `:build` dependencies because they must be present at runtime. Static libraries need only be present as a separate file at build time and are thereafter included in a package's binaries so they may be `:build` dependencies.

The boost package is a weird case because it contains both header-only and compiled libraries. Packages that only use header-only boost libraries may use boost as a `:build` dependency because that code is embedded in the package's binaries (though by the C++ preprocessor, instead of by the linker). Packages that link dynamically against a compiled boost library must declare boost as a normal dependency.

**Comment by tseemann** [comment]
I'm guessing that there are many erroneous ```:build``` directives in packages that just happen to work because the library etc remains installed?

**Comment by iml** [comment]
There are, but good tests should help catch those since the bot will remove build-only dependencies prior to the `brew test` step.
