### ISSUE TITLE
simpleitk fails to build on 10.10.3

### ISSUE THREAD

**Issue by bfontaine** [Homebrew/homebrew-science#2554]
```
==> Installing homebrew/science/simpleitk
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
==> Downloading https://downloads.sourceforge.net/project/simpleitk/SimpleITK/0.8.0/Source/SimpleITK-0.8.0.tar.gz
==> Downloading from http://cznic.dl.sourceforge.net/project/simpleitk/SimpleITK/0.8.0/Source/SimpleITK-0.8.0.tar.gz
######################################################################## 100,0%
==> cmake . -DCMAKE_C_FLAGS_RELEASE= -DCMAKE_CXX_FLAGS_RELEASE= -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/simpleitk/0.8.0 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON
==> make install
-- Processing json files...done
-- Configuring incomplete, errors occurred!
See also "/tmp/simpleitk20150723-26205-155vc33/SimpleITK-0.8.0/CMakeFiles/CMakeOutput.log".
See also "/tmp/simpleitk20150723-26205-155vc33/SimpleITK-0.8.0/CMakeFiles/CMakeError.log".
make: *** [cmake_check_build_system] Error 1
```

Logs: https://gist.github.com/fb4f992c44ffba48ab3d

**Comment by dpo** [comment]
Any chance that you could gist `CMakeOutput.log` and `CMakeError.log`?

**Comment by bfontaine** [comment]
@dpo: https://gist.github.com/bfontaine/449a98f4872890e55c38

**Comment by dpo** [comment]
I guess we're missing `needs :cxx11`?! @iMichka

**Comment by iMichka** [comment]
I'll have a look.

Note that Simpleitk is not building for the moment because of a bug which appeared with sing 3.0.6 (https://github.com/swig/swig/issues/475). I will make a patch which uses USE_SYSTEM_SWIG=OFF so that simpleitk's internal swig is used; which is 3.0.5.

**Comment by iMichka** [comment]
The c++11 thing is probably not what we are looking for. It happens in some "Performing Test" block; these are c++ code snippets which are compiled at the beginning to guess what compiler is there and if patches need to be applied internally.

The selected swig version is 3.0.6 in the logs. Could you please uninstall swig and try to go back to 3.0.5 ? This made the build pass on my side.

I guess we can no more go back to swig 3.0.5 on homebrew's side ? SimpleITK will need to be patched  to make it work.

Note: The formula also needs this line which is missing (after the PYTHON_LIBRARY line):
```
args << "-DPYTHON_INCLUDE_DIR='#{%x(python-config --prefix).chomp}/include/python2.7'"
```
because the include dir is also not correctly found by cmake.

**Comment by iMichka** [comment]
There should be swig update to 3.0.7 soon, which fixes the problem.

Once it is out I'll update the swig and the simpleITK formula.

**Comment by iMichka** [comment]
simpleITK 0.9 was just merged. It uses the superbuild setup which should make the build much more robust. Could you test again and close this bug if everything is fine ?

**Comment by iMichka** [comment]
Ping @bfontaine this has been good on my side for some time. Could you please re-test ? I will also update to version 0.10 later anyway.
