### ISSUE TITLE
Homebrew should support formulae that install R packages

### ISSUE THREAD

**Issue by lmrodriguezr** [Homebrew/homebrew-science#2559]
The Nonpareil bottle doesn't install the R Nonpareil package.

**Comment by tdsmith** [comment]
As discussed at https://github.com/Homebrew/homebrew-science/pull/2567#issuecomment-125051191, this is because the nonpareil formula calls `R CMD INSTALL`, which has the effect of writing outside of nonpareil's prefix, so it isn't picked up in the bottle (and breaks Homebrew policy).

Fixing R packaging in Homebrew will be a lot of work. We can plausibly remove the nonpareil bottle in the interim if the package isn't useful without the R component.

**Comment by lmrodriguezr** [comment]
I think removing the bottle is the most sensible solution. Compilation time and resources for Nonpareil are small, and that way the R package can still be installed.

Out of curiosity, is there a better way to do it? I could write a patch for the Nonpareil installer, but I cannot think of a way to fix this that doesn't involve writing outside of nonpareil's prefix.

**Comment by tdsmith** [comment]
> Out of curiosity, is there a better way to do it?

I expect that there is. We configure Python so that its default module search path is relative to HOMEBREW_PREFIX and not Python's private prefix, so that it searches in e.g. /usr/local/lib/python2.7/site-packages and not /usr/local/Cellar/python/2.7.10/lib/python2.7/site-packages. This means that if a formula installs /usr/local/Cellar/some_formula/1.2.3/lib/python2.7/site-packages/foo.py, it gets symlinked into /usr/local/lib/python2.7/site-packages, and python finds it just fine.

"A lot of work" was probably an overstatement; someone needs to figure out which switches to feed R at build time and what we can do to influence INSTALL's behavior, and we need to make a quick change to the Homebrew symlinking code. Depending on R's release schedule, it should make sense to make those changes with the next R minor release since packages don't normally persist across minor releases.

**Comment by tdsmith** [comment]
Minor releases are scheduled for spring: https://developer.r-project.org/ so we probably don't want to wait that long.

Doing this on a micro release would also make a lot of sense, since, right now, packages are installed to R's private prefix by default and are lost on any version increment.

**Comment by dpo** [comment]
At the moment, uninstalling `nonpareil` doesn't uninstall its R bindings.

**Comment by tdsmith** [comment]
If `R_HOME/site-library` exists, R will use it. It does not exist by default. We should symlink `R_HOME/site-library` to `HOMEBREW_PREFIX/lib/R/x.y/site-library`. For framework builds, `R_HOME` is `prefix/R.framework/Versions/3.2/Resources`.

We can instruct `R CMD install` to install a package to a particular library using e.g. `--library=#{lib}/R/x.y/site-library`.

We can ask R for its x.y version with `Rscript -e 'cat(as.character(getRversion()[1,1:2]))'`.

**Comment by tdsmith** [comment]
The remaining outstanding task is to fix nonpareil.

**Comment by lmrodriguezr** [comment]
@tdsmith I think your changes in ec63b61feb154b29579231fe11fd18645872b10b fixed nonpareil.
