### ISSUE TITLE
R compiled via brew doesn't compile X11 or tcl-tk support

### ISSUE THREAD

**Issue by dalewsteele** [Homebrew/homebrew-science#2683]
I've been happily using R compiled via brew on Yosemite. However, after installing xquartz (either via brew or via package installer) and tcl-tk, I find that the compiled version does not compile either X11 or tcltk support.

Any suggestions?

brew config:
https://gist.github.com/dalewsteele/250296800892bbb3b044

capabilities():
https://gist.github.com/dalewsteele/f049986b59f98566f472

**Comment by tdsmith** [comment]
What options did you give `brew install` when you installed R? Can you share `brew gist-logs r`? X11 is not included by default but tcl-tk should be.

**Comment by dalewsteele** [comment]
Believe I did:

brew install gcc
brew cask install xquartz
brew install tcl-tk
brew install r --with-openblas

https://gist.github.com/anonymous/0203c97434c193c35292

What is the brew install option that includes X11?

Thanks.

**Comment by tdsmith** [comment]
What's `find /usr/local -name tcl.h` give you? It shouldn't be picking up Homebrew's tcl-tk because we don't support doing that but it's not attempting to link against the system framework.

`--with-x11` (`brew info r` will tell you)

if you aren't really sure you want openblas (without --with-openblas you get Apple's Accelerate framework, which is usually faster) and X, you'll get a bottle if you drop all of the options, which should be built against system Tcl/Tk

**Comment by dalewsteele** [comment]
Thanks for the information.  Suspect I'll be happy with the binary bottle, which installs just fine when I install without the (--with-openblas option).  However, fwiw:

Dales-iMac:~ dsteele$ find /usr/local -name tcl.h
/usr/local/Cellar/tcl-tk/8.6.4/include/tcl.h

I tried:
dsteele$ brew install r --with-x11

--> make quit with an error: see gist log:

https://gist.github.com/1be98797e9c25f28a0b4

**Comment by dalewsteele** [comment]
sorry - closed inadvertently. Does seem like there a problem (at least on my system) with
install r  --with-x11

**Comment by tdsmith** [comment]
looks like it needs cairo with-x11 to enable X support: https://gist.github.com/anonymous/1be98797e9c25f28a0b4#file-02-make-L561-L570

**Comment by sjackman** [comment]
Try `brew install linuxbrew/xorg/xorg cairo r --with-x11`
