### ISSUE TITLE
brew pull - Failure while executing: /usr/bin/curl -f#LA 

### ISSUE THREAD

**Issue by tseemann** [Homebrew/homebrew-science#2854]
Every second formula I try to pull into Brewsci I get the following error:

```
brew pull --bottle https://github.com/Homebrew/homebrew-science/pull/2808
######################################################################## 100.0%
==> Applying patch
Applying: Weighbour 1.2 (new formula)
==> Patch closes issue #2808
Error: Failure while executing: /usr/bin/curl -f#LA Homebrew\ 0.9.5\ (Ruby\ 2.0.0-481;\ OS\ X\ 10.10.5) --silent --fail -o /dev/null -I https://github.com/BrewTestBot/homebrew-science/compare/homebrew:master...pr-2808
```

I'm at a loss.

**Comment by dpo** [comment]
@tseemann The issue is with bottle upload to Bintray. In your PR, if you access the details on the build on the Jenkins interface

![screen shot 2015-10-08 at 9 46 53](https://cloud.githubusercontent.com/assets/38760/10368093/aa9393ce-6da1-11e5-874f-7faadd24e00b.PNG)

and click "Downstream build view"

![screen shot 2015-10-08 at 9 48 10](https://cloud.githubusercontent.com/assets/38760/10368131/e2f9d3d6-6da1-11e5-971f-15b1d4544120.PNG)

you'll see that the bottle upload job has failed:

![screen shot 2015-10-08 at 9 49 19](https://cloud.githubusercontent.com/assets/38760/10368136/e6618bfe-6da1-11e5-913f-afa196b55cdb.PNG)

 In my experience, that's because either

1. the formula is new and several builds were requested in the PR (e.g., some fixes were made to the formula), or
2. the PR updates a formula but the revision number wasn't bumped.

Either way, what happens is that bottles on Bintray can't be overwritten (I'm not sure why), so the upload job fails. Revision bumps update the bottle file name.

Here's how to resolve the problem: log in to Bintray and search for the formula name in the `homebrew/bottles-science` repository.

![screen shot 2015-10-08 at 9 55 22](https://cloud.githubusercontent.com/assets/38760/10368331/c558f9fa-6da2-11e5-95f1-04fe896e4f71.PNG)

Click on the formula and then on "Files", and you'll see the list of bottles. Identify the most recent ones (those supposed to be updated by the PR) and delete them one by one (can't batch-delete).

![screen shot 2015-10-08 at 9 51 12](https://cloud.githubusercontent.com/assets/38760/10368210/3a2faf54-6da2-11e5-94b7-e1e7bc9e7580.PNG)

Once that's done, return to "Downstream build view" of the Jenkins interface from the PR on Github. Click on the job number

![screen shot 2015-10-08 at 9 49 19](https://cloud.githubusercontent.com/assets/38760/10368403/0af9f9dc-6da3-11e5-8661-7b3b0d80ed32.PNG)

and then "retry":

![screen shot 2015-10-08 at 9 52 26](https://cloud.githubusercontent.com/assets/38760/10368235/5bfe381c-6da2-11e5-9df0-b5488afbe398.PNG)

If all goes well, the upload job should go through and you'll be able to `brew pull --bottle`.

**Comment by tseemann** [comment]
Wow - I did not expect such an illustrative and detailed answer - thanks @dpo !

We should move this into some Markdown docs for Admins? @sjackman

**Comment by sjackman** [comment]
Fantastic answer, Dominique. Yes, please do copy this post to the Wiki.

**Comment by sjackman** [comment]
@Homebrew/owners

**Comment by DomT4** [comment]
> Either way, what happens is that bottles on Bintray can't be overwritten (I'm not sure why), so the upload job fails.

Published files can't be overwritten automatically by the CI for security reasons. If you've started `brew pull`-ing something and the files have been published, you need to manually log in and remove them. You can remove them via `curl` if you'd like to as well, but the web UI is pleasant enough.

> and then "retry":

We tend to do `rebuild` rather than `retry`, but it doesn't *seem* to matter.

> Would you like to copy the above explanation of failed bottle uploads to the Homebrew maintainer documentation?

It could be useful, aye. I'd like to segregate the maintainer documentation out from the user documentation a bit more as well; I don't think it's useful or helpful for most users to check the docs folder and see a bunch of stuff intended for us.

**Comment by dpo** [comment]
I agree.
