### ISSUE TITLE
Re unable to install gubbins using brew with the following error on Ubuntu 14.04 similar to 2883 ? any thoughts

### ISSUE THREAD

**Issue by svanhal71** [Homebrew/homebrew-science#2975]
running install

Numerical Python (NumPy) is not installed.

This package is required for many Biopython features.  Please install
it before you install Biopython. You can install Biopython anyway, but
anything dependent on NumPy will not work. If you do this, and later
install NumPy, you should then re-install Biopython.

You can find NumPy at http://www.numpy.org

READ THIS: https://github.com/Homebrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/homebrew/homebrew-science/issues

**Comment by tseemann** [comment]
@svanhal71  Can you please clarify what your question is?

**Comment by svanhal71** [comment]
Thanks 

I am trying to install Gubbins on a linux system with Ubuntu 14.04 using linuxbrex brew as described in https://github.com/sanger-pathogens/gubbins/blob/master/INSTALL.md and can't get it to install

brew install python3 works fine.
when I brew install gubbins it gets to the final steps but crashes with the error message

Already downloaded: /gubbins--nose-1.3.7.tar.gz
==> python3 -c import setuptools... --no-user-cfg install --prefix=/.linuxbrew/Cellar/gubbins/1.4.1_1/libexec/vendor --single-v
==> Downloading https://pypi.python.org/packages/source/b/biopython/biopython-1.65.tar.gz
Already downloaded: /Homebrew/gubbins--biopython-1.65.tar.gz
==> python3 -c import setuptools... --no-user-cfg install --prefix=/.linuxbrew/Cellar/gubbins/1.4.1_1/libexec/vendor --single-v
Last 15 lines from /home/christian/.cache/Homebrew/Logs/gubbins/02.python3:
--prefix=/.linuxbrew/Cellar/gubbins/1.4.1_1/libexec/vendor
--single-version-externally-managed
--record=installed.txt

running install

Numerical Python (NumPy) is not installed.

This package is required for many Biopython features.  Please install
it before you install Biopython. You can install Biopython anyway, but
anything dependent on NumPy will not work. If you do this, and later
install NumPy, you should then re-install Biopython.

You can find NumPy at http://www.numpy.org
READ THIS: 
https://github.com/Homebrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/homebrew/homebrew-science/issues


I tried the following:

uninstalling numpy, biopython and getting brew to install - same error message
uninstalling and installing from source - gibbuns crashes with not enough memory message 
have contacted the sanger without much joy; they suggested a possible issue may be how python was installed initially - so have installed from a new/fresh ubuntu operating system same issue 

Any thoughts how to get around this and get Gubbins to work?

Thanks
Sebastian

**Comment by andrewjpage** [comment]
A user reported the other day that this fixed the the above error on their installation of linuxbrew & gubbins:

   mkdir -p /home/xxx/.local/lib/python3.5/site-packages
     echo 'import site; site.addsitedir("/home/xxx/.linuxbrew/lib/python3.5/site-packages")' >> /home/xxx/.local/lib/python3.5/site-packages/homebrew.pth

**Comment by dpo** [comment]
@svanhal71 Do you have Numpy installed? Try `pip3 install numpy` or `brew install numpy --with-python3`.

**Comment by danknight** [comment]
I have been experiencing the same issue on two separate Bio Linux installs. The above does not remedy the numpy error. Any other solutions?

**Comment by andrewjpage** [comment]
Fixed by PR https://github.com/Homebrew/homebrew-science/issues/3409

**Comment by ksw9** [comment]
Hi,
I am also running into similar errors when I try to install Gubbins using LinuxBrew.  After following the instructions on the Gubbins GitHub, after trying 
brew install gubbins

I recieve the following errors:
unning install

Numerical Python (NumPy) is not installed.

This package is required for many Biopython features.  Please install
it before you install Biopython. You can install Biopython anyway, but
anything dependent on NumPy will not work. If you do this, and later
install NumPy, you should then re-install Biopython.

You can find NumPy at http://www.numpy.org
READ THIS: https://github.com/Linuxbrew/brew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-science/issues

These open issues may also help:
gubbins - Failed to import the site module (since python 3.4 -> 3.5) https://github.com/Homebrew/homebrew-science/issues/3490
Re unable to install gubbins using brew with the following error on Ubuntu 14.04 similar to 2883 ? any thoughts https://github.com/Homebrew/homebrew-science/issues/2975


I have tried the fix mentioned above by Andrew but am still running into errors.  Any advice would be fantastic, thank you!  Is there a way to install Gubbins by cloning directly from the Github repo?

Thank you!

**Comment by ksw9** [comment]
I just wanted to follow up--are others having similar issues?  Is there a recommended way to install without LinuxBrew?
Thank you!

**Comment by danknight** [comment]
Hi ksw9,

This issue was remedied with a new update for Gubbins.
See issue #159 https://github.com/sanger-pathogens/gubbins/issues/159

Cheers
Dan

**Comment by dpo** [comment]
Is this resolved?

**Comment by svanhal71** [comment]
Yes the new package is installing using brew.

Thanks

**Comment by dpo** [comment]
Thanks.
