### ISSUE TITLE
Syntax for depends_on cask :build?

### ISSUE THREAD

**Issue by brainstorm** [Homebrew/homebrew-science#3148]
Hello Homebrew-science,

I have a tricky academic software I would like to wrap on homebrew/linuxbrew, @neurolabusc's MRIcroGL.

Unfortunately it has some exotic dependencies, such as a FreePascal compiler, Lazarus:

https://github.com/caskroom/homebrew-cask/blob/master/Casks/lazarus.rb

The standard `fpc` compiler included on Homebrew does not cut it:

https://github.com/Homebrew/homebrew/blob/master/Library/Formula/fpc.rb

Since `lazbuild` seems to be needed, which only seems to be present in the Homebrew Cask version.

Therefore, I'm looking at syntax like this, so that the `build` dependency does not get pulled in as part of the target system where it is installing:

 `depends_on :cask "homebrew/cask/lazarus" => :build`

The closest I got is this one:

https://github.com/caskroom/homebrew-cask/blob/master/doc/CASK_LANGUAGE_REFERENCE.md#depends_on-stanza-details

PD: The "build system" of MRICroGL is non-portable/non-automated, but that's another story: https://github.com/neurolabusc/MRIcroGL/blob/master/_osx.command.

**Comment by dpo** [comment]
You would have a better chance if you submitted your issue to [Homebrew core](https://github.com/Homebrew/homebrew/issues).

**Comment by tdsmith** [comment]
You would want to write e.g. a `LazarusRequirement`. You can see some example Requirements in /usr/local/Library/Homebrew/requirements. You can add a LazarusRequirement class to the top of a formula file and then depend on it like `depends_on LazarusRequirement => :build`.

**Comment by brainstorm** [comment]
I think I will pass on this one for now.

The codebase does require some serious heavy lifting first, such as fixing the **very broken** "build system" first:

https://github.com/neurolabusc/MRIcroGL/blob/master/_osx.command

When this software could be built by easy means such a simple "make", then it would deserve some packaging. As it is now, it's not worth it.

@neurolabusc

**Comment by neurolabusc** [comment]
Respectfully, I disagree with your comment about it being broken. I  think it is a matter of choosing the correct tool for a problem. If you want to use a simple make command for volume rendering you should choose my Github vx project. If you want a Volume renderer in Objective C you should use my Xcode MRIcro project. However, the former has a crude (glut) user interface and the latter is not cross platform. On the other hand, my MRIcroGL is write-once compile everywhere which natively builds to the desired widgetset (Cocoa, Carbon, Windows API, QT or GTK). The result is an executable that feels native, does not require 100's of Mb of libraries, has a clean code base, etc. Personally, I prefer this approach to using QT or wxWidgets. In one sense, my project is not a good match for Homebrew since it does not require a package manager: users can run the executables without any dependencies. People who want to develop can use an IDE that is native to their OS and easily port it to any other OS. I am happy to agree that this approach is atypical, and not a great match for your desired goal of porting to homebrew, but that was never my intention. My desire was to write a very light cross-platform OS wrapper for my GLSL-based shaders.

**Comment by brainstorm** [comment]
Respectfully as well, while I agree with some of your analysis, putting hardcoded user paths is a very clear and typical symptom of broken deployment:

```
cp dcm2niix /Users/rorden/Documents/osx/dcm2niix
cp dcm2niix /Users/rorden/Documents/osx/MRIcroGL.app/Contents/MacOS/dcm2niix
cp dcm2niix /Users/rorden/Documents/osx/MRIcroGL64.app/Contents/MacOS/dcm2niix
(...)
```

And also the antithesis of portable or cross-platform as you mention.

**Comment by brainstorm** [comment]
And yes, @neurolabusc, there's nothing wrong with the core of your software, it rocks as a visualizer! It's just the way of finishing that distribution in "today's ways that are more typical" that needs some love:

1) Reasonable/standard **automated** build system.
2) Release engineering/shipping other than putting binary .DMG's in your lab's page.

Takes some time but it's worth it if you want more uptake/userbase of your system if you are interested in something more than publishing papers about it.

**Comment by neurolabusc** [comment]
If you want relative paths why not make a request or submit a patch. Please see online for a new osx.command file that builds the executable. The previous command file built a lot of other tools and packaged them for NITRC. 
----
#!/bin/sh
# change to working directory to location of command file: http://hints.macworld.com/article.php?story=20041217111834902
here="`dirname \"$0\"`"
cd "$here" || exit 1
lazbuild ./simplelaz.lpr --cpu=x86_64 --ws=cocoa
strip ./MRIcroGL
mv ./MRIcroGL ./DistroOSX/MRIcroGL.app/Contents/MacOS/
cp ./Distro/*.gz ./DistroOSX
cp ./Distro/*.pdf ./DistroOSX
---
With regards to distribution, I am happy to have an expert with home-brew help add an additional method for distribution. At the moment users have several options:
 1.) OSX users can get MRIcro from the App store. This is convenient, but the sandboxing requirements make this awkward for many of the popular neuroimaging formats (NIfTI hdr/img; DICOM) where a single document is spread over multiple files which the user has not selected. This explains why my app store software inconveniently requires the user to select the images.
 2.) Michael Hanke has added nice support for NeuroDebian install of MRIcroGL.
 3.) I distribute the executables for OSX, Windows and Linux on NITRC. I like the help forum, the licensing information and the distribution. It looks like this serves about 350 downloads a month which seems pretty good for a specialized tool (https://www.nitrc.org/project/stats/?group_id=889).

Again, I would be happy to have your help in providing an additional method for distribution that other users may find helpful. But please bear in mind that I have a lot of commitments to my own scientific endeavors, so tools like home-brew are foreign to me.
