### ISSUE TITLE
OpenCV 3.1.0 Java Link Problem

### ISSUE THREAD

**Issue by tdsmith** [Homebrew/homebrew-science#3268]
_From @qianliwang on January 28, 2016 3:48_

The Opencv3 formula update from 3.0.0 to 3.1.0. After install --with-java, the java system.loadlibrary("opencv_java310") failed. Even system.load("/usr/local/Cellar/.../java/libopencv_java310.so") failed. 

_Copied from original issue: Homebrew/homebrew#48537_

**Comment by aleksey-suprun** [comment]
I have the similar issue and I'm pretty sure that this issue because of wrong library format. Java expect to handle "libopencv_java310.dylib" library but "libopencv_java310.so" was built by brew.

This can be easily proved by making a quick test program to call `System.mapLibraryName("Boo")`. In my case the output is `libBoo.dylib`.

Nevertheless, `System.load("/usr/local/Cellar/opencv3/3.1.0_1/share/OpenCV/java/libopencv_java310.so");` works for me. So I can use it as workaround for now.

**Comment by iMichka** [comment]
opencv has been migrated to homebrew-core. Please that version and report any issue back there. Thanks.
