### ISSUE TITLE
Aliases

### ISSUE THREAD

**Issue by ScottKolo** [Homebrew/homebrew-science#3334]
Howdy all,

I was wondering what the best way to add an alias here would be. Base homebrew has an [Aliases folder](https://github.com/Homebrew/homebrew/tree/master/Library/Aliases) - can such a mechanism be added here? I'll gladly make a pull request to add the symlink.

The formula of interest is suite-sparse (it's probably a good idea to have a suitesparse alias, with no hyphen).

Thanks!

**Comment by dpo** [comment]
Why? The official library name is SuiteSparse, which is the name of the formula. If the file were `suitesparse.rb`, Homebrew would expect a formula named `Suitesparse`, not `SuiteSparse`.

**Comment by ScottKolo** [comment]
That's why I think it needs an alias. Since SuiteSparse is the official library name, it's a bit silly that "brew install SuiteSparse" doesn't work. But instead of renaming the formula file (which would cause problems as you pointed out), it would be nice to just add an alias for suitesparse -> suite-sparse.rb.

**Comment by dpo** [comment]
`brew install SuiteSparse` doesn't work because there's no file named `SuiteSparse.rb`. Don't confuse the file name, the formula name, and the package name. I really don't see what problem the alias would solve. Brew has command completion, so typing `brew install suite[TAB]` completes to `suite-sparse`. Besides, there are other formulas out there named similarly, e.g., `suite-sparse421` and `suite-sparse-julia`.

**Comment by ScottKolo** [comment]
I appreciate the command completion, but perhaps take a look at RGui. `brew install RGui` doesn't work because the file name is `r-gui.rb`, not `rgui.rb`. If I type `brew install r[TAB]` I get 139 possible suggestions. Having an alias `rgui -> r-gui.rb` would help here, would it not? And that way the formula would remain named `RGui`.

**Comment by tdsmith** [comment]
Taps support aliases, yes; create a directory `Aliases` containing symlinks that point to the formula file, i.e. Aliases/suitesparse -> ../suite-sparse.rb.
