### ISSUE TITLE
Can PAUP* be included in homebrew-science ?

### ISSUE THREAD

**Issue by annikals** [Homebrew/homebrew-science#3369]
http://paup.csit.fsu.edu/downl.html
I need this for an assignment but have no clue

**Comment by dpo** [comment]
Thanks for the suggestion! One of us might get to it if there's sufficient interest, but because we're all doing this in our spare time, it will certainly be more efficient if you submit a PR. Have a look at the [formula cookbook](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Formula-Cookbook.md) and don't hesitate to ask!

**Comment by Moisan** [comment]
The mac version only targets PowerPC and the unix version requires an order to Sinauer Associates [but they do not distribute it anyway](http://paup.csit.fsu.edu/order.html). Unless you have another way to obtain the source, I don't think this can be added to homebrew.

**Comment by jonchang** [comment]
The open source version of PAUP* was announced about 2 years ago but is still vaporware. If and when it comes out feel free to reopen this issue and I'll take a look at creating a formula for it.
