### ISSUE TITLE
[Request] Xdmf formula

### ISSUE THREAD

**Issue by amoose136** [Homebrew/homebrew-science#3795]
Building [Xdmf](http://xdmf.org/index.php/Get_Xdmf) on MacOS/OS X has been an annoying process for me. I'd like to manage an Xdmf install via Brew but I'm not very good with Ruby and the last time I tried making a formula I didn't really get anywhere in a general manner.  I know it requires Swig and HDF5 and there are formulas for both of these already available but making a formula that will work on systems other than my own is daunting because I can barely get it to install properly as is. I need a formula that also creates the python bindings.

**Comment by amoose136** [comment]
Note: added $40 bounty on bountysource.com

**Comment by tdsmith** [comment]
We won't accept a formula to homebrew-science until there's a stable release version, i.e. pending resolution of https://gitlab.kitware.com/xdmf/xdmf/issues/1.

In the meantime, you can run `brew install tdsmith/xdmf/xdmf --HEAD`.

**Comment by albeanth** [comment]
@tdsmith does `brew install tdsmith/xdmf/xdmf --HEAD` still work? I am receiving the following error when trying to execute this brew install.

```
...
patching file CMakeLists.txt
Hunk #1 FAILED at 166.
Hunk #2 succeeded at 212 with fuzz 1 (offset 18 lines).
1 out of 2 hunks FAILED -- saving rejects to file CMakeLists.txt.rej
Error: Failure while executing: /usr/bin/patch -g 0 -f -p1 
```

Before these errors, the following warning is displayed a number of times:

```
==> Installing xdmf from tdsmith/xdmf
Warning: Use hdf5 instead of deprecated homebrew/science/hdf5
```

I have HDF5 1.10.1_2 installed via `brew install HDF5`

Do you have any advice on how to remedy this?

**Comment by tdsmith** [comment]
Doesn't look like it. :) I'd try removing the patches and correcting the depends_on. Good luck.

**Comment by albeanth** [comment]
Just in case anyone else runs across this thread trying to get XDMF going on a mac I figured I would leave a reply with how to install xdmf from source. I don't know the ins and outs of brew formulas and treat them as rather black boxes so I figured it might be easiest for me to just try this from the source.

So! With HDF5 through homebrew, `brew install HDF5`, I needed to tell CMake where to find HDF5 by setting the [HDF5_ROOT environment variable](https://cmake.org/cmake/help/v3.0/module/FindHDF5.html)

`export HDF5_ROOT="/usr/local/Cellar/HDF5/1.10.1_2"`

Then, CMake had issues finding the development headers and spat out that it couldn't find "HDF5_C_INCLUDE_DIR". After a bit of googling, it turns out these are in "/usr/local/Cellar/hdf5/1.10.1_2/lib" and is set at the command line by invoking:

`-DHDF5_C_INCLUDE_DIR=/usr/local/Cellar/hdf5/1.10.1_2/lib`

For me, adding in those two things lead to XDMF being successfully built.  However, as of now XDMF fails to `make`. I'm getting an undeclared identifier error towards the end of the make... Will post if/when I get it figured out....
