### ISSUE TITLE
Any chance of including BEAST-2 in homebrew-science & updating the version?

### ISSUE THREAD

**Issue by bobtodd** [Homebrew/homebrew-science#4141]
I've installed [`BEAST-2`](https://github.com/jonchang/homebrew-biology/blob/master/beast2.rb) via the [`homebrew-biology`](https://github.com/jonchang/homebrew-biology) cask that @jonchang set up.  But while attempting to install other add-ons (the BEAUTi add-ons menu is actually blank... any suggestions?), I noticed the formula installs version 2.1.1.  But the latest version [seems to be](http://beast2.org/) 2.4.3.  I have 2 questions:
1. Would it be possible to update the version of `BEAST-2` installed via Homebrew?
2. Is there any particular reason that `BEAST-1` is part of the `homebrew-science` collection, but not `BEAST-2`?

Thanks in advance for any feedback.

**Comment by jonchang** [comment]
Hi @bobtodd, I've updated my BEAST 2 formula to v2.4.3. You can install the new version after running `brew update`.

BEAST 2 isn't part of homebrew-science mainly because no one has submitted a pull request for it. I haven't done it myself because I don't use it for my own work and therefore cannot justify the pain of shepherding it into homebrew-science.

**Comment by ilovezfs** [comment]
@jonchang why do you anticipate it would be painful? It appears to be the best case scenario: no dependencies, no reverse dependencies, and no options:
```
Josephs-MacBook-Pro:~ joe$ brew uses homebrew/science/beast
Josephs-MacBook-Pro:~ joe$ brew deps homebrew/science/beast
Josephs-MacBook-Pro:~ joe$ brew info homebrew/science/beast
homebrew/science/beast: stable 1.8.3, HEAD
Bayesian Evolutionary Analysis Sampling Trees
http://beast.bio.ed.ac.uk/
Not installed
From: https://github.com/Homebrew/homebrew-science/blob/master/beast.rb
==> Caveats
Examples are installed in:
  /usr/local/opt/beast/examples/
Josephs-MacBook-Pro:~ joe$ brew uses --include-optional --include-build beast
Josephs-MacBook-Pro:~ joe$ 
```

**Comment by jonchang** [comment]
@ilovezfs No offense to you or any of the other hardworking homebrew-science maintainers, but I have often experienced an incredible delay in getting PRs accepted. See #3628 that fixes build errors that date back to July of last year. It's really not a big deal for me since `brew pull xxx && brew install` is not super difficult, but I hope you can understand why I'm reticent about submitting patches.

**Comment by jonchang** [comment]
@ilovezfs Also, just to clarify -- BEAST2 is a separate app from BEAST1 despite the name and version numbers. Any installs therefore need to support both apps on the same machine without conflicts.

**Comment by ilovezfs** [comment]
@jonchang yep, I more-than-understand that lol. I was just worried it was something technical with beast2. Let's get your garli PR merged and I'll clean it up if necessary afterward.

**Comment by bobtodd** [comment]
Thanks @jonchang.  You rock!  Just installed the updated version and it seems to be working great.

As for the hornet's nest of placing `BEAST-2` in `homebrew-science`, I was just working off of the install prompt:

```bash
==> Caveats
This install coexists with BEASTv1 as all scripts are suffixed with '-2':

    beast-2 -help
```

But I can understand it might be much more complicated.  I'm just learning to use `BEAST-2` myself, so I don't yet know enough to say anything helpful.

Thanks *very* much to you and @ilovezfs for the help.

**Comment by ilovezfs** [comment]
@jonchang any luck with a BEAST2 formula?

**Comment by jonchang** [comment]
I mean, it's already written. I'll just open a PR for the formula from my tap.

**Comment by ilovezfs** [comment]
@jonchang cool thanks jon
