### ISSUE TITLE
Can't remove packages

### ISSUE THREAD

**Issue by giriarteS** [Homebrew/homebrew-science#4664]
### Indicate troubleshooting steps taken

- [x] Ran `brew update` and retried your prior step? 
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step? I ran brew doctor but I was not sure about removing files.
- [x] Checked that a similar issue hasn't already been filed? 

#### Brief summary of issue:

[description.txt](https://github.com/Homebrew/homebrew-science/files/626164/description.txt)

#### Gist with output of `brew doctor`:

[brew_doctor.txt](https://github.com/Homebrew/homebrew-science/files/626174/brew_doctor.txt)

#### Output of `brew config`:

[brew_config.txt](https://github.com/Homebrew/homebrew-science/files/626165/brew_config.txt)

**Comment by jonchang** [comment]
Hi @giriarteS, it looks like there's a merge conflict going on, did you modify `repeatscout.rb` at some point in the past? If you are not worried about losing your changes then you can simply do `brew untap homebrew/science && brew tap homebrew/science`

**Comment by autosquid** [comment]
A similar error:


```
Error: Formulae found in multiple taps:
 * homebrew/core/arpack
 * homebrew/science/arpack

```

**Comment by iMichka** [comment]
@giriarteS I hope that @jonchang 's instructions helped you. It really looks like you edited the repeatscout.rb file, this is why there is a conflict.

@autosquid I am not sure how your error is similar. Please fill in a new bug for this, using the issue template. Thanks

I will close this bug so that the issue tracker does not get cluttered. Please open new issues if there are still problems.
