### ISSUE TITLE
Issues building opencv3 Linux bottles

### ISSUE THREAD

**Issue by iMichka** [Homebrew/homebrew-science#5336]
This is a follow-up from #5186

There are multiple things to do:

1) `depends_on "openblas" unless OS.mac?` can be added, and `WITH_LAPACK=OFF` removed.

2) Try to fix the AVX2 failure. I had a look at this. There are a bunch of ENABLE_AVX flags that can be used, but they are not working. They are also marked as deprecated option in opencv3 master. Building with `--HEAD` works, so this has been fixed upstream :). In my opinion we should ask for a new release. In that case we need to replace the ENABLE_AVX flags by CPU_BASELINE_DISABLE.
See: https://github.com/opencv/opencv/blob/a57d144076222d2cd689671c80890e4ef41c4e64/cmake/OpenCVCompilerOptimizations.cmake

3) We should disable the QUICKTIME option on Linux, cmake is telling me that this option is not valid (as a warning only).

@sjackman @timotheecour

**Comment by iMichka** [comment]
I asked for a new release here: https://github.com/opencv/opencv/issues/7985

**Comment by alalek** [comment]
Hi,

I'm a member of OpenCV development team. There are some my comments below:

2.
> CPU_BASELINE_DISABLE

Probably it is not a good idea to use this variable at all. Please use `CPU_BASELINE` variable instead to enable AVX/SSE4.2/etc options and use "nothing" to disable of unsupported optimizations (most of them are disabled by default).

What does `Hardware::CPU.avx` mean in the expression below?
> args << "-DENABLE_AVX=ON" if Hardware::CPU.avx?

If "Hardware::CPU" flags are similar to GCC "-march=native" mode (and not controlled via some brew flags), then probably it is better to use `CPU_BASELINE=HOST` (or `NATIVE` - they are alias). This detection should work fine with modern GCC/Clang/Intel compilers.
Also you can pass compiler options via `CMAKE_CXX_FLAGS` (`-mavx`/`-msse4.2`/`-mno-avx2`etc). In this case, it is better to use `CPU_BASELINE=DETECT` argument.
Probably `DETECT` should work for binary packages (bottles) too.


BTW, OpenCV team doesn't plan to make release in the nearest future.
Anyway, "commit" releases are available for anyone by GitHub: https://github.com/opencv/opencv/archive/f34b2f7b8d10271d0e16bcab174bdacd51365f4f.zip
They are not similar to "--HEAD", because they are fixed and will not be changed on the next week.

**Comment by sjackman** [comment]
Thanks for your response, Alexander. For our binary bottles we target `-march=core2` without SSE 4.2. Does this look right?
```ruby
if build.bottle?
    args << "-DCPU_BASELINE=core2"
    args << "-DENABLE_AVX=OFF"
else
    args << "-DCPU_BASELINE=HOST"
    args << "-DENABLE_AVX=ON" if Hardware::CPU.avx?
end
```

**Comment by sjackman** [comment]
Yes, `Hardware::CPU.avx?` returns whether this machine's CPU has support for AVX.

**Comment by alalek** [comment]
Looks good. But "ENABLE_AVX" should not be used anymore. Also OpenCV CMake scripts doesn't know about "core2" (the current optimization flags configuration is based on instructions sets).

> `-march=core2` without SSE 4.2

GCC docs states [this](https://gcc.gnu.org/onlinedocs/gcc-6.3.0/gcc/x86-Options.html#x86-Options):
> ‘core2’
Intel Core 2 CPU with 64-bit extensions, MMX, SSE, SSE2, SSE3 and SSSE3 instruction set support. 

The nearest OpenCV argument via `CPU_BASELINE` variable is: `-DCPU_BASELINE=SSSE3` (the current OpenCV default for [x86-64](https://github.com/opencv/opencv/blob/a57d144076222d2cd689671c80890e4ef41c4e64/cmake/OpenCVCompilerOptimizations.cmake#L246)). Compiler option will be "-mssse3". But this is not equal to required `-march=core2`.

Probably this should work (if there is no conflict for `CMAKE_CXX_FLAGS`):
```
if build.bottle?
    args << "-DCMAKE_CXX_FLAGS='-march=core2'"  # assumes that this flag works with other brew compilers (Clang/MacOS)
    args << "-DCPU_BASELINE=DETECT" # do not touch compiler flags, just autodetect and use available optimizations
else
    args << "-DCPU_BASELINE=HOST"  # will use compiler "-march=native" flag and detects available optimizations
end
```

**Comment by sjackman** [comment]
Thanks. I forgot this additional bit of information. We found it necessary to use `-DOPENCV_EXTRA_CXX_FLAGS='-march=core-avx2'` to avoid
`error: '_mm_cvtps_ph' was not declared in this scope`.
See https://github.com/Homebrew/homebrew-science/blob/master/opencv3.rb#L125
and https://github.com/RoboSherlock/robosherlock/issues/78#issuecomment-274469830

**Comment by iMichka** [comment]
I oped a pull request with the changes here: #5348

Let's continue the discussion there.
