### ISSUE TITLE
Blast v2.6.0 on Linux producing inconsistent results, can I install older version?

### ISSUE THREAD

**Issue by nextgenusfs** [Homebrew/homebrew-science#5347]
Using LinuxBrew I'm seeing some inconsistent results from Blast+ 2.6.0 on Ubuntu, specifically the `tblastn` command is yielding different results on Linux than it does on Mac.  There was a segfault issue with `tblastn v2.4.0`, so I'm guessing there is yet another bug but I can't get it to spit an error at me, just finds many fewer hits than it should be.  I was wondering if there is a way to install an older version of blast, i.e. pre-v2.4.0 using linuxbrew or not?  Seems like the `brew versions` command is deprecated, but not sure if that would have worked anyway?  Perhaps I can just go back to the `apt-get` version, but would be easier for other linuxbrew packages that rely on blast to change versions from home-brew.

**Comment by jonchang** [comment]
Well, ideally we would be able to track down and fix the bug. It would be good to be able to tell if this is an issue on our side (i.e., our build system passing incorrect flags or something causing the error) or whether this is an upstream bug with blast. I recommend contacting the blast developers or email the blast mailing list to see if anyone else is encountering this specific situation. A reproducible test case would help immensely.

Unfortunately we don't support installing older versions; if anything goes wrong we won't be able to help you out due to our limited resources.

**Comment by nextgenusfs** [comment]
Thanks, I will try to test the NCBI 2.6.0 binary release vs the home-brew build and see if there is a difference.  I've noticed the problem on a rather large dataset, so will also see if I can't get a smaller test case.  My guess is it is an upstream issue and not a build problem, but mostly I was curious about installing older versions.  I know one can do `brew switch` if you have previously installed older versions, but that doesn't help me when building a docker container.

**Comment by jonchang** [comment]
Ok, feel free to file a new issue if you get a test case / show that our build system is causing problems. For the future note that you can use the `brew pin` command to prevent formulae your workflow depends on from being upgraded automatically.
