### ISSUE TITLE
opencv3 won't build for python2 and python3

### ISSUE THREAD

**Issue by walchko** [Homebrew/homebrew-science#5900]
### Indicate troubleshooting steps taken

- [x ] Ran `brew update` and retried your prior step?
- [ x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ x] Checked that a similar issue hasn't already been filed?
- [ x] Looked up the software bug tracker if reporting a build error?
- [ x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

#### Brief summary of issue:

formula won't let me build both python2 and python3 libraries of opencv3

### Formula Requests:

**The quickest way to get a new formula into Homebrew is to file a [Pull Request](https://github.com/Homebrew/homebrew-science/pulls)**.

We will consider your request but it may be closed if it's something we're not actively planning to work on.

in opencv3.rb I commented out:

    if build.with?("python3") && build.with?("python")
      # Opencv3 Does not support building both Python 2 and 3 versions
      odie "opencv3: Does not support building both Python 2 and 3 wrappers"
    end

and now it built and works fine. You might want to remove this. I built it with:

    brew install opencv3 --with-ffmpeg --without-numpy --with-nonfree --with-python3 --with-tbb --with-contrib

I have both libraries and can load them in both python2 and python3. Also a quick test of both (grabbing images) works fine. 

Again, not sure why you did this, but it isn't correct ... you can build and install both fine.

**Comment by iMichka** [comment]
Hi. It's me that added this check lately, see 435b6e5c471fd4061af376e88737b8895e7affa0

The problem, if I remember well, is that opencv3 relies on PYTHONPATH being set, and there is only one PYTHONPATH (there is no PYTHONPATH3). So adding these lines fixed builds for some people. Because if you enable both Pythons at the same time, you will have PYTHONPATH defined as Python2, breaking the Python3 build.
I am worried that removing these lines will break some builds, while fixing others.

There is this long outstanding issue here which is still open:
https://github.com/Homebrew/homebrew-science/issues/5463

The best would that upstream should not rely on PYTHONPATH, but allow to pass this path as a Cmake flag.

The opencv3 python bindings are a huge mess, and have been for long. The homebrew maintainers (me included) have not much time to invest so pull requests are welcome. Somebody needs to dig through the opencv3 cmake files and come up with a real fix.

**Comment by iMichka** [comment]
Closing this in favour of the discussion in #5463.
