### ISSUE TITLE
Associate DOI with published science software

### ISSUE THREAD

**Issue by sjackman** [Homebrew/homebrew-science#781]
I would like to associate a [DOI](http://en.wikipedia.org/wiki/Digital_object_identifier) with each formula associated with a published scientific article. The purpose is to facilitate preparing citations and downloading PDFs of open-access articles. I suggest a `doi` extension to the Homebrew DSL, such as

``` ruby
  doi "10.1101/gr.089532.108"
```

which resolves to http://dx.doi.org/10.1101/gr.089532.108
which resolves to http://genome.cshlp.org/content/19/6/1117

@samueljohn @dpo @iml @adamv I'd appreciate your feedback. Would this extension live in Homebrew-core or Homebrew-science? (What's the accepted way of referring to Homebrew-core?)

Cheers,
Shaun

**Comment by tseemann** [comment]
@adamv I've just caught up with this thread and its relatives. Like @sjackman I would be very excited to see such a feature. Bioinformatics has 100s of new tools every year, and even the popular ones are often used but not cited properly, and if Brew can help alleviate this problem it would be wonderful.

This sort of controlled meta-data (maybe with ontologies for some tags) would be something that differentiates Brew from other packaging systems. The DOI is particularly useful due to the linkages outside Brew that can be made. DOI => Papers => Authors => Institutes => Science Fields etc.

I'm consistently putting #doi tags in all formulae I write in anticipation of this feature being implemented one day.
